# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_ui/stringify_desktop_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stringify(object):
    def setupUi(self, Stringify):
        Stringify.setObjectName("Stringify")
        Stringify.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        Stringify.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Stringify)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 561, 121))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.input_text_field = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text_field.setGeometry(QtCore.QRect(40, 250, 281, 211))
        self.input_text_field.setObjectName("input_text_field")
        self.output_text_field = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text_field.setGeometry(QtCore.QRect(480, 250, 281, 211))
        self.output_text_field.setObjectName("output_text_field")
        self.stringify_button = QtWidgets.QPushButton(self.centralwidget)
        self.stringify_button.setGeometry(QtCore.QRect(360, 330, 89, 25))
        self.stringify_button.setObjectName("stringify_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(360, 390, 89, 25))
        self.reset_button.setObjectName("reset_button")
        self.delimeter_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.delimeter_comboBox.setGeometry(QtCore.QRect(370, 270, 71, 25))
        self.delimeter_comboBox.setObjectName("delimeter_comboBox")
        self.delimeter_comboBox.addItem("")
        self.delimeter_comboBox.addItem("")
        self.delimeter_comboBox.addItem("")
        self.delimeter_comboBox.addItem("")
        self.delimeter_comboBox.addItem("")
        self.delimeter_comboBox.addItem("")
        Stringify.setCentralWidget(self.centralwidget)

        self.retranslateUi(Stringify)
        QtCore.QMetaObject.connectSlotsByName(Stringify)

    def retranslateUi(self, Stringify):
        _translate = QtCore.QCoreApplication.translate
        Stringify.setWindowTitle(_translate("Stringify", "Stringify desktop"))
        self.label.setText(
            _translate(
                "Stringify",
                "Convert any collection of objects to strings separated by any delimeter of your choice.",
            )
        )
        self.input_text_field.setPlaceholderText(
            _translate("Stringify", "Paste or type your raw text here!!")
        )
        self.stringify_button.setText(_translate("Stringify", "stringify"))
        self.reset_button.setText(_translate("Stringify", "reset"))
        self.delimeter_comboBox.setToolTip(_translate("Stringify", "choose a delimeter!"))
        self.delimeter_comboBox.setItemText(0, _translate("Stringify", ","))
        self.delimeter_comboBox.setItemText(1, _translate("Stringify", ";"))
        self.delimeter_comboBox.setItemText(2, _translate("Stringify", ":"))
        self.delimeter_comboBox.setItemText(3, _translate("Stringify", "|"))
        self.delimeter_comboBox.setItemText(4, _translate("Stringify", "space"))
        self.delimeter_comboBox.setItemText(5, _translate("Stringify", "newline"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Stringify = QtWidgets.QMainWindow()
    ui = Ui_Stringify()
    ui.setupUi(Stringify)
    Stringify.show()
    sys.exit(app.exec_())
